"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Activity, ArrowRight, BrainCircuit, CheckCircle2, CircleAlert, Clock3, Gauge, RefreshCw, Server, Zap } from "lucide-react";
import { SiGooglegemini } from "@icons-pack/react-simple-icons";
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageShell } from "@/components/page-shell";
import { apiFetch, type ApiEnvelope } from "@/lib/api";
import { formatDate, formatNumber } from "@/lib/utils";
import type { LogRow } from "@/components/logs-table";
import type { ProviderRow } from "@/components/provider-status-card";

interface UsageAggregate { id:string; label:string; provider?:string; requests:number; errors:number; totalTokens:number; estimatedCost:number; averageLatencyMs:number; errorRate:number }
interface ModelPerformanceEntry { modelAlias:string; provider:string; requests:number; averageLatencyMs:number; throughput:number; errorRate:number }
interface Stats { requestsToday:number; requestsLast5h:number; totalRequests:number; totalTokens:number; averageLatencyMs:number; errorRate:number; estimatedCost:number; activeProviders:number; usageByProvider:UsageAggregate[]; modelPerformance:ModelPerformanceEntry[] }
interface ProviderQuotaStatus { provider:string; status:string; exactProviderResetAt:string|null; estimatedFiveHourResetAt:string|null; lastQuotaEvent:null|{createdAt:string;modelAlias:string;errorCode:string|null;errorMessage:string|null} }
type Health="healthy"|"degraded"|"down"|"idle";

const healthStyle:Record<Health,{label:string;dot:string;badge:string}>={
 healthy:{label:"Healthy",dot:"bg-success",badge:"border-success/20 bg-success/10 text-success"},
 degraded:{label:"Degraded",dot:"bg-warning",badge:"border-warning/20 bg-warning/10 text-warning"},
 down:{label:"Unavailable",dot:"bg-danger",badge:"border-danger/20 bg-danger/10 text-danger"},
 idle:{label:"Idle",dot:"bg-faint",badge:"border-line bg-white/[.03] text-faint"}
};
function providerHealth(provider:ProviderRow,rows:LogRow[]):Health{if(!provider.enabled)return"down";const recent=rows.filter(r=>r.provider===provider.name&&Date.now()-new Date(r.createdAt).getTime()<900000).slice(0,6);if(!recent.length)return"idle";const failures=recent.filter(r=>r.status!=="success").length;if(failures>=3)return"down";if(failures)return"degraded";return"healthy"}
function ProviderLogo({name}:{name:string}){const n=name.toLowerCase();if(n.includes("gemini")||n.includes("google"))return <SiGooglegemini className="h-4 w-4"/>;if(n.includes("openai")||n.includes("gpt"))return <BrainCircuit className="h-4 w-4"/>;return <span className="text-[10px] font-bold">Z</span>}
function StatCard({label,value,detail,icon:Icon,success=false}:{label:string;value:string;detail:string;icon:typeof Activity;success?:boolean}){return <div className="rounded-lg border border-line bg-panel p-5 "><div className="flex items-start justify-between"><div><p className="text-xs font-medium text-faint">{label}</p><p className="mt-3 text-2xl font-semibold tracking-[-.035em] text-ink">{value}</p></div><div className={`grid h-9 w-9 place-items-center rounded-md border ${success?"border-success/20 bg-success/10 text-success":"border-accent-border bg-white/[.04] text-dim"}`}><Icon className="h-4 w-4"/></div></div><p className="mt-2 text-xs text-faint">{detail}</p></div>}
const tooltipStyle={background:"var(--bg-elevated)",border:"1px solid var(--border-default)",borderRadius:12,fontSize:12,color:"var(--text-primary)"};

export default function DashboardPage(){
 const[stats,setStats]=useState<Stats|null>(null),[providers,setProviders]=useState<ProviderRow[]>([]),[logs,setLogs]=useState<LogRow[]>([]),[quota,setQuota]=useState<ProviderQuotaStatus|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 function load(){setLoading(true);Promise.all([apiFetch<Stats>("/admin/stats"),apiFetch<ApiEnvelope<ProviderRow[]>>("/admin/providers"),apiFetch<ApiEnvelope<LogRow[]>>("/admin/logs"),apiFetch<ProviderQuotaStatus>("/admin/quota")]).then(([s,p,l,q])=>{setStats(s);setProviders(p.data);setLogs(l.data);setQuota(q);setError("")}).catch((e:Error)=>setError(e.message)).finally(()=>setLoading(false))}
 useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);
 const providerRows=useMemo(()=>providers.map(provider=>{const rows=logs.filter(r=>r.provider===provider.name);return{provider,latest:rows[0],usage:stats?.usageByProvider.find(r=>r.label===provider.name||r.provider===provider.name),health:providerHealth(provider,logs)}}),[providers,logs,stats]);
 const healthy=providerRows.filter(r=>r.health==="healthy").length;
 const overall:Health=providerRows.some(r=>r.health==="down")?"down":providerRows.some(r=>r.health==="degraded")?"degraded":healthy?"healthy":"idle";
 const traffic=(stats?.usageByProvider??[]).filter(x=>x.requests>0).slice(0,5),totalTraffic=traffic.reduce((a,b)=>a+b.requests,0)||1,models=(stats?.modelPerformance??[]).slice(0,8);
 const chartData=useMemo(()=>logs.slice(0,48).reverse().map(r=>({time:new Date(r.createdAt).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"}),latency:r.latencyMs})),[logs]);
 const quotaActive=Boolean(quota?.lastQuotaEvent&&(!quota.estimatedFiveHourResetAt||new Date(quota.estimatedFiveHourResetAt).getTime()>Date.now()));
 if(loading&&!stats)return <PageShell><div className="flex min-h-[60vh] items-center justify-center text-sm text-faint">Loading dashboard…</div></PageShell>;
 if(error||!stats)return <PageShell><div className="rounded-md border border-danger/20 bg-danger/5 p-4 text-sm text-danger">{error||"Service data unavailable"}</div></PageShell>;
 return <PageShell><div className="mx-auto max-w-[1500px] space-y-6 pb-10">
  <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-3 flex items-center gap-2 text-xs text-faint"><span className={`h-2 w-2 rounded-full ${healthStyle[overall].dot}`}/><span>{healthStyle[overall].label}</span><span>·</span><span>updates every 30 seconds</span></div><h1 className="text-3xl font-semibold tracking-[-.045em] text-ink">Overview</h1><p className="mt-2 text-sm text-faint">The useful service signals, without dashboard noise.</p></div><button onClick={load} disabled={loading} className="inline-flex h-9 items-center gap-2 rounded-md border border-line bg-panel px-3 text-xs text-dim  hover:text-ink"><RefreshCw className={`h-3.5 w-3.5 ${loading?"animate-spin":""}`}/>Refresh</button></header>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Service status" value={healthStyle[overall].label} detail={`${healthy} of ${providers.filter(p=>p.enabled).length} providers healthy`} icon={Server} success/><StatCard label="Requests today" value={formatNumber(stats.requestsToday)} detail={`${formatNumber(stats.requestsLast5h)} in the last 5 hours`} icon={Activity}/><StatCard label="Average latency" value={`${formatNumber(stats.averageLatencyMs)} ms`} detail="Across completed requests" icon={Gauge}/><StatCard label="Success rate" value={`${Math.max(0,100-stats.errorRate*100).toFixed(1)}%`} detail={`${formatNumber(stats.totalRequests)} recorded requests`} icon={CheckCircle2} success/></section>
  <section className="grid gap-4 xl:grid-cols-[1.55fr_.75fr]">
   <div className="rounded-lg border border-line bg-panel p-5"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-sm font-semibold text-ink">Latency trend</h2><p className="mt-1 text-xs text-faint">Latest completed model requests</p></div></div><div className="h-[270px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="latencyFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--accent)" stopOpacity={.25}/><stop offset="100%" stopColor="var(--accent)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.05)" vertical={false}/><XAxis dataKey="time" tick={{fill:"var(--text-muted)",fontSize:10}} axisLine={false} tickLine={false} minTickGap={36}/><YAxis tick={{fill:"var(--text-muted)",fontSize:10}} axisLine={false} tickLine={false} width={42}/><Tooltip contentStyle={tooltipStyle}/><Area type="monotone" dataKey="latency" stroke="var(--accent)" strokeWidth={2} fill="url(#latencyFill)" dot={false}/></AreaChart></ResponsiveContainer></div></div>
   <div className="rounded-lg border border-line bg-panel p-5"><div className="mb-4"><h2 className="text-sm font-semibold text-ink">Traffic split</h2><p className="mt-1 text-xs text-faint">Requests by provider</p></div><div className="mx-auto h-[170px] max-w-[220px]"><ResponsiveContainer><PieChart><Pie data={traffic} dataKey="requests" nameKey="label" innerRadius={54} outerRadius={76} paddingAngle={3} stroke="none">{traffic.map((_,i)=><Cell key={i} fill={["var(--accent)","var(--info)","var(--warning)","var(--success)","var(--danger)"][i%5]}/>)}</Pie><Tooltip contentStyle={tooltipStyle}/></PieChart></ResponsiveContainer></div><div className="space-y-3">{traffic.map((r,i)=><div key={r.id} className="flex items-center gap-3 text-xs"><span className="h-2 w-2 rounded-full" style={{background:["var(--accent)","var(--info)","var(--warning)","var(--success)","var(--danger)"][i%5]}}/><span className="min-w-0 flex-1 truncate text-dim">{r.label}</span><span className="font-medium text-ink">{((r.requests/totalTraffic)*100).toFixed(1)}%</span></div>)}</div></div>
  </section>
  <section className="grid gap-4 xl:grid-cols-[.82fr_1.18fr]">
   <div className="rounded-lg border border-line bg-panel"><div className="flex items-center justify-between border-b border-hair px-5 py-4"><div><h2 className="text-sm font-semibold text-ink">Provider health</h2><p className="mt-1 text-xs text-faint">Current routing availability</p></div><Link href="/providers" className="flex items-center gap-1 text-xs text-faint hover:text-ink">View all <ArrowRight className="h-3 w-3"/></Link></div><div className="divide-y divide-hair">{providerRows.map(({provider,latest,usage,health})=><div key={provider.id} className="grid grid-cols-[1fr_auto] gap-4 px-5 py-4"><div className="flex min-w-0 items-center gap-3"><div className="grid h-9 w-9 shrink-0 place-items-center rounded-md border border-line bg-elevated text-dim"><ProviderLogo name={provider.name}/></div><div className="min-w-0"><div className="truncate text-sm font-medium text-ink">{provider.name}</div><div className="mt-1 text-xs text-faint">{formatNumber(usage?.requests??0)} requests · {latest?`${formatNumber(latest.latencyMs)} ms`:"no latency"}</div></div></div><span className={`self-center rounded-full border px-2 py-1 text-[10px] font-medium ${healthStyle[health].badge}`}>{healthStyle[health].label}</span></div>)}</div></div>
   <div className="rounded-lg border border-line bg-panel"><div className="flex items-center justify-between border-b border-hair px-5 py-4"><div><h2 className="text-sm font-semibold text-ink">Model performance</h2><p className="mt-1 text-xs text-faint">Most-used routes and reliability</p></div><Link href="/models" className="flex items-center gap-1 text-xs text-faint hover:text-ink">Manage <ArrowRight className="h-3 w-3"/></Link></div><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left"><thead><tr className="border-b border-hair text-[10px] uppercase tracking-[.12em] text-faint"><th className="px-5 py-3 font-medium">Model</th><th className="px-4 py-3 font-medium">Provider</th><th className="px-4 py-3 font-medium">Latency</th><th className="px-4 py-3 font-medium">Requests</th><th className="px-5 py-3 font-medium">Reliability</th></tr></thead><tbody className="divide-y divide-hair">{models.map(m=>{const success=Math.max(0,100-m.errorRate*100);return <tr key={`${m.provider}-${m.modelAlias}`} className="transition hover:bg-hover"><td className="px-5 py-3 text-sm font-medium text-ink">{m.modelAlias}</td><td className="px-4 py-3"><div className="flex items-center gap-2 text-xs text-dim"><ProviderLogo name={m.provider}/>{m.provider}</div></td><td className="px-4 py-3 text-xs text-dim">{formatNumber(m.averageLatencyMs)} ms</td><td className="px-4 py-3 text-xs text-dim">{formatNumber(m.requests)}</td><td className="px-5 py-3"><div className="flex items-center gap-3"><div className="h-1.5 flex-1 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-accent" style={{width:`${success}%`}}/></div><span className="w-12 text-right text-xs text-dim">{success.toFixed(1)}%</span></div></td></tr>})}</tbody></table></div></div>
  </section>
  <section className="grid gap-4 lg:grid-cols-[1fr_.7fr]"><div className="rounded-lg border border-line bg-panel"><div className="flex items-center justify-between border-b border-hair px-5 py-4"><div><h2 className="text-sm font-semibold text-ink">Recent activity</h2><p className="mt-1 text-xs text-faint">Latest request outcomes</p></div><Link href="/logs" className="flex items-center gap-1 text-xs text-faint hover:text-ink">Open logs <ArrowRight className="h-3 w-3"/></Link></div><div className="divide-y divide-hair">{logs.slice(0,6).map(row=><div key={row.id} className="flex items-center gap-3 px-5 py-3.5"><div className={`grid h-7 w-7 place-items-center rounded-lg ${row.status==="success"?"bg-success/10 text-success":"bg-danger/10 text-danger"}`}>{row.status==="success"?<CheckCircle2 className="h-3.5 w-3.5"/>:<CircleAlert className="h-3.5 w-3.5"/>}</div><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-ink">{row.modelAlias} · {row.provider}</p><p className="mt-1 truncate text-[11px] text-faint">{row.status==="success"?`${formatNumber(row.latencyMs)} ms`:row.errorMessage||row.errorCode||"Request failed"}</p></div><span className="text-[10px] text-faint">{new Date(row.createdAt).toLocaleTimeString("de-DE",{hour:"2-digit",minute:"2-digit"})}</span></div>)}</div></div><div className="space-y-4">{quotaActive&&quota?.lastQuotaEvent?<div className="rounded-lg border border-warning/20 bg-warning/[.055] p-5"><div className="flex gap-3"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0 text-warning"/><div><h3 className="text-sm font-semibold text-ink">Quota attention</h3><p className="mt-2 text-xs leading-5 text-faint">{quota.lastQuotaEvent.errorMessage||"Provider quota is currently limited."}</p>{quota.estimatedFiveHourResetAt?<p className="mt-3 flex items-center gap-2 text-xs text-warning"><Clock3 className="h-3.5 w-3.5"/>Reset {formatDate(quota.estimatedFiveHourResetAt)}</p>:null}</div></div></div>:<div className="rounded-lg border border-success/20 bg-success/[.055] p-5"><div className="flex gap-3"><Zap className="mt-0.5 h-4 w-4 shrink-0 text-success"/><div><h3 className="text-sm font-semibold text-ink">Routing looks stable</h3><p className="mt-2 text-xs leading-5 text-faint">No active quota incident or critical provider failure detected.</p></div></div></div>}<div className="rounded-lg border border-line bg-panel p-5"><p className="text-xs text-faint">Estimated cost</p><p className="mt-2 text-xl font-semibold text-ink">${stats.estimatedCost.toFixed(4)}</p><p className="mt-3 text-xs text-faint">Based on recorded token usage.</p></div></div></section>
 </div></PageShell>
}
